### ISSUE TITLE
Not indexing redirects

### ISSUE THREAD

**Issue by Krisseck** [lindylearn/aboutideasnow#6]
It looks like the site is not indexing when the pages are 301 redirected.

In case of my site, I have:

- polso.info/ideas, returns 200
- polso.info/now, returns 301 to /projects

And the crawler only finds the ideas page.

![image](https://github.com/lindylearn/aboutideasnow/assets/471887/def1857b-66fc-4496-aac7-fcf0d0b2c979)

**Comment by phgn0** [comment]
Yep we were deriving the post type (about, ideas, or now) based on the redirected URL of the page, and /my-projects didn't match any of them.

I just fixed this with https://github.com/lindylearn/aboutideasnow/commit/47ae533319b463a162d9e17f95e1ae978ef8de64, and indexed your site.

Thanks so much for reporting this!
