### ISSUE TITLE
Wrong "last updated" displayed after indexing site

### ISSUE THREAD

**Issue by spencewenski** [lindylearn/aboutideasnow#8]
I indexed my site which I just added about/ideas/now pages to. I included the last update time with the string `Last updated: 27 Feb 2024`. However, when I indexed my site, it said the last update time was 26 Feb 2024.

Site: https://spencewenski.com
Technology: NextJS + [MUI](https://mui.com)
Browser: Firefox
OS: MacOS (apple silicon)
Time index request submitted: ~4:45 pm US Pacific time on 27 Feb 2024

<img width="267" alt="Screenshot 2024-02-27 at 4 56 17 PM" src="https://github.com/lindylearn/aboutideasnow/assets/3319370/1070389d-c98b-42ca-aff3-446e139dea4f">
<img width="632" alt="Screenshot 2024-02-27 at 4 56 32 PM" src="https://github.com/lindylearn/aboutideasnow/assets/3319370/2986b60b-640d-4dda-929e-33feb53db866">

**Comment by phgn0** [comment]
This seems like a timezone issue. Your posts actually are saved with `2024-02-27T00:00:00.000Z` in the database. 👀
